# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs shiftleft source code scan on demo-app repo
      - name: Run ShiftLeft Source Code Scan
        env: 
          CHKP_CLOUDGUARD_ID: cf8eed92-abaf-48ad-94e8-3a8668d5c2ea
          CHKP_CLOUDGUARD_SECRET: jju394fcckup44b1c7q8g6qa
        run: |
          chmod +x ./shiftleft
          git clone https://github.com/fabrimagic72/malware-samples
          ./shiftleft code-scan -s . -r -2003 -e 1df96cdc-d49b-4784-a650-678cafee5164

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
